workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate fresh Android folders
        script: flutter create --project-name shift_alarm_app --platforms=android .
      - name: Overwrite AndroidManifest with permissions
        script: |
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.CAMERA" />
              <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
              <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
              <application
                  android:label="shift_alarm_app"
                  android:name="${applicationName}"
                  android:icon="@mipmap/ic_launcher">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <meta-data
                        android:name="io.flutter.embedding.android.NormalTheme"
                        android:resource="@style/NormalTheme"
                        />
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>
          EOF
      - name: Enable Java 8 Desugaring for Notifications
        script: |
          cat <<EOF >> android/app/build.gradle
          android {
              compileOptions {
                  coreLibraryDesugaringEnabled true
                  sourceCompatibility JavaVersion.VERSION_1_8
                  targetCompatibility JavaVersion.VERSION_1_8
              }
          }
          dependencies {
              coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:1.2.2"
          }
          EOF
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Debug APK
        script: flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
